//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RWViewImageRaster.rc
//
#define IDS_PROJNAME                    100
#define IDC_POINTER_COPY                105
#define IDS_NOSHORTCUT                  110
#define IDS_MENU_LAYEREFFECT            111
#define IDS_EDITTOOL_MOVESELECT         112
#define IDS_TOOLNAME_SELECT             112
#define IDS_EDITTOOL_FREEHAND           113
#define IDS_TOOLNAME_PENCIL             113
#define IDS_EDITTOOL_LINE               114
#define IDS_TOOLNAME_LINE               114
#define IDS_EDITTOOL_RECTANGLE          115
#define IDS_TOOLNAME_RECTANGLE          115
#define IDS_EDITTOOL_FILLRECT           116
#define IDS_FILLSTYLE_SOLID_NAME        116
#define IDS_EDITTOOL_FLOODFILL          117
#define IDS_TOOLNAME_FLOODFILL          117
#define IDS_EDITTOOL_DROPPER            118
#define IDS_TOOLNAME_DROPPER            118
#define IDS_EDITTOOL_ELLIPSE            119
#define IDS_TOOLNAME_ELLIPSE            119
#define IDS_EDITTOOL_TEXT               120
#define IDS_TOOLNAME_TEXT               120
#define IDS_EDITTOOL_CURVE              121
#define IDS_TOOLNAME_CURVE              121
#define IDS_EDITTOOL_SHADOW             122
#define IDS_TOOLNAME_PSHADOW            122
#define IDS_EDITTOOL_POLYGON            123
#define IDS_TOOLNAME_POLYGON            123
#define IDS_EDITTOOL_EXTRUSION          124
#define IDS_EDITTOOL_TRANSFORMATION     125
#define IDS_TOOLNAME_TRANSFORMATION     125
#define IDS_EDITTOOL_HOTSPOT            126
#define IDS_CFGID_2DEDIT_CONTEXTMENU_NAME 126
#define IDS_EDITTOOL_EMBOSS             127
#define IDS_VIEWNAME                    128
#define IDS_MENU_DRAWINGTOOLS           128
#define IDS_IMGEDIT_VIEWNAME            129
#define IDS_CFGID_IMGVIEW_CUSTOMBACKGROUND_NAME 130
#define IDS_MENU_DRAWINGTOOL_DESC       130
#define IDS_CFGID_IMGVIEW_CUSTOMBACKGROUND_DESC 131
#define IDS_CLIPBOARDDATA_NAME          131
#define IDS_CFGID_IMGVIEW_BACKGROUNDCOLOR_NAME 132
#define IDS_MENU_DRAWMODE               132
#define IDS_CFGID_IMGVIEW_BACKGROUNDCOLOR_NAME2 133
#define IDS_CFGID_IMGVIEW_BACKGROUNDCOLOR_DESC 133
#define IDS_CFGID_DRAWMODE_TYPE_NAME    133
#define IDS_CUSTCFG_DEFAULTCOLOR        134
#define IDS_CFGID_DRAWMODE_TYPE_DESC    134
#define IDS_CUSTCFG_MORECOLORS          135
#define IDS_CFGVAL_DRAWMODE_RASTERIZATION 135
#define IDS_EDITTOOLS                   136
#define IDS_STDBUTTONS                  136
#define IDS_CFGVAL_DRAWMODE_BLENDING    136
#define IDS_CUSTCFG_COLORNAMES          137
#define IDS_MENUCOMMANDSSELECTIONDOCUMENT_NAME 137
#define IDS_CFGID_2DEDIT_TOOLCOLORSYNC_NAME 138
#define IDS_CFGID_2DEDIT_TOOLSYNC_NAME  138
#define IDS_CFGID_2DEDIT_TOOLCOLORSYNC_DESC 139
#define IDS_CFGID_2DEDIT_TOOLSYNC_DESC  139
#define IDS_COLORPICKER_VIEWNAME        142
#define IDS_CFGID_CLRPICK_COLORINDEX_NAME 143
#define IDS_CFGID_CLRPICK_COLORINDEX_DESC 144
#define IDS_CFGID_2DEDIT_COLOR1SYNC_NAME 144
#define IDS_CFGVAL_COLORINDEX_PRIMARY_NAME 145
#define IDS_CFGID_2DEDIT_COLOR1SYNC_DESC 145
#define IDS_CFGVAL_COLORINDEX_SECONDARY_NAME 146
#define IDS_CFGID_2DEDIT_COLOR2SYNC_NAME 146
#define IDS_TOOLPROPS_VIEWNAME          147
#define IDS_TOOL                        148
#define IDS_CFGID_CLRPICK_GUITYPE_NAME  154
#define IDS_CFGID_CLRPICK_GUITYPE_DESC  155
#define IDS_CFGVAL_CPGTYPE_SLIDERS      156
#define IDS_CFGVAL_CPGTYPE_AREAS        157
#define IDS_CFGID_SUBCOMMANDS_NAME      158
#define IDS_CFGID_SUBCOMMANDS_DESC      159
#define IDS_CFGID_TOOLLIST_FILTER_NAME  160
#define IDS_CFGID_TOOLLIST_FILTER_DESC  161
#define IDS_CFGVAL_TL_RAW               162
#define IDS_CFGVAL_TL_HOTSPOT           163
#define IDS_MOVESELECT_ORIGINALSIZE     164
#define IDS_MENU_RESTORESELECTION_DESC  164
#define IDS_MOVESELECT_ENTIREAREA       165
#define IDS_MENU_STRETCHSELECTION_DESC  165
#define IDS_CFGID_ALLIMAGEONOSEL_NAME   166
#define IDS_CFGID_ALLIMAGEONOSEL_DESC   167
#define IDS_RE_CONTEXTHELP              168
#define IDS_HELP_COLORAREAHS            169
#define IDS_HELP_COLORAREALA            170
#define IDS_CFGID_2DEDIT_COLOR2SYNC_DESC 171
#define IDS_MENU_COLOR                  172
#define IDS_MENU_COLOR1_NAME            173
#define IDS_MENU_COLOR1_DESC            174
#define IDS_MENU_COLOR2_NAME            175
#define IDS_MENU_COLOR2_DESC            176
#define IDS_MENU_COLORSET_DESC          177
#define IDS_HELP_COLORSLIDER            178
#define IDS_HELP_COLOREDIT              179
#define IDS_MENU_RASTERSMOOTH_NAME      180
#define IDS_MENU_RASTERSMOOTH_DESC      181
#define IDS_MENU_RASTERBINARY_NAME      182
#define IDS_MENU_RASTERBINARY_DESC      183
#define IDS_MENU_BLENDOVER_NAME         184
#define IDS_MENU_BLENDOVER_DESC         185
#define IDS_MENU_BLENDREPLACE_NAME      186
#define IDS_MENU_BLENDREPLACE_DESC      187
#define IDS_MENU_BLENDUNDER_NAME        188
#define IDS_MENU_BLENDUNDER_DESC        189
#define IDS_HELP_NOFILTERING            190
#define IDS_HELP_LINEARFILTERING        191
#define IDS_HELP_CUBICFILTERING         192
#define IDS_HELP_FINISH                 193
#define IDS_HELP_TEXT                   194
#define IDS_HELP_FONT                   195
#define IDS_HELP_WIDTH                  196
#define IDS_HELP_SINGLELINE             197
#define IDS_HELP_POLYLINE               198
#define IDS_HELP_MITERJOIN              199
#define IDS_HELP_ROUNDJOIN              200
#define IDS_HELP_BEVELJOIN              201
#define IDC_BUTTON1                     202
#define IDS_HELP_CONTURE                202
#define IDC_CGRE_GESTURES               202
#define IDC_CT_COLOR1                   202
#define IDC_ASG_COLOR1                  202
#define IDC_CGIMGVIEW_USECUSTOM         203
#define IDS_HELP_FILL                   203
#define IDC_CT_COLOR2                   203
#define IDS_HELP_ALTERNATEFILL          204
#define IDS_HELP_RADIUS                 205
#define IDC_CGRE_CONTEXTMENU            205
#define IDS_HELP_SQUARECAP              206
#define IDC_CGRE_SUBCONFIG              206
#define IDS_HELP_ROUNDEDCAP             207
#define IDC_LE_TOOLBAR                  207
#define IDS_HELP_BUTTCAP                208
#define IDC_CG_OPERATION                209
#define IDS_HELP_TOLERANCE              209
#define IDC_CG_OPCONFIG                 210
#define IDS_HELP_SOLIDCOLOR             210
#define IDI_EDITTOOL_FLOODFILL1         211
#define IDS_HELP_GRADIENT               211
#define IDS_HELP_BLUR                   212
#define IDC_ET_ANTIALIAS                213
#define IDS_HELP_NEARDENS               213
#define IDC_ET_PAINTOVER                214
#define IDS_HELP_FARDENS                214
#define IDC_CT_TOOLBAR                  214
#define IDS_CFGID_2DEDIT_SELECTIONSYNC_NAME 215
#define IDC_CT_LIST                     215
#define IDC_ET_REPLACE                  216
#define IDS_CFGID_2DEDIT_SELECTIONSYNC_DESC 216
#define IDS_CFGID_2DEDIT_FILLSTYLESYNC_NAME 217
#define IDC_ET_NOOPTIONS                218
#define IDS_CFGID_2DEDIT_FILLSTYLESYNC_DESC 218
#define IDS_CFGVAL_DRAWMODE_COORDINATES 219
#define IDS_CFGVAL_DRAWMODE_SHAPEFILL   220
#define IDD_EDITTOOL_NOOPTIONS          221
#define IDC_RADIO1                      221
#define IDC_ET_CONTURE                  221
#define IDS_MENU_COORDSFLOAT_NAME       221
#define IDC_RADIO2                      222
#define IDC_ET_FILL                     222
#define IDS_MENU_COORDSFLOAT_DESC       222
#define IDC_RADIO3                      223
#define IDD_EDITTOOL_CLOSEDSHAPE        223
#define IDC_ET_ALTERNATEFILL            223
#define IDS_MENU_COORDSINT_NAME         223
#define IDD_EDITTOOL_FREEHAND           224
#define IDS_MENU_COORDSINT_DESC         224
#define IDC_CT_SHORTCUT                 224
#define IDS_MENU_SHAPEOUTLINE_NAME      225
#define IDC_CT_SHORTCUTLABEL            225
#define IDS_MENU_SHAPEOUTLINE_DESC      226
#define IDC_CGCOLORPICKER_COLORTYPE     227
#define IDD_CONFIGGUI_EDITTOOLPROPERTIES 227
#define IDS_MENU_SHAPEFILL_NAME         227
#define IDC_COMBO2                      228
#define IDD_CONFIGGUI_RASTEREDIT        228
#define IDS_MENU_SHAPEFILL_DESC         228
#define IDC_CT_RASTERMODE               228
#define IDD_EDITTOOL_LINE1              229
#define IDS_MENU_SHAPECOMBINED_NAME     229
#define IDC_CGETP_SYNCGRP               230
#define IDS_MENU_SHAPECOMBINED_DESC     230
#define IDC_CGRE_SYNCGRP                231
#define IDS_FILLSTYLE_LINEAR_NAME       231
#define IDC_CGRE_AUTOZOOM               232
#define IDS_FILLSTYLE_RADIAL_NAME       232
#define IDC_CGRE_GRID                   233
#define IDS_FILLSTYLE_CONICAL_NAME      233
#define IDS_MENU_FINISHDRAWING          234
#define IDC_ET_SOLIDCOLOR               235
#define IDD_CONFIGGUI_SELDOC            235
#define IDS_MENU_FINISHDRAWING_NAME     235
#define IDC_ET_GRADIENT                 236
#define IDD_CONFIGGUI_DRAWINGTOOLLIST   236
#define IDS_MENU_FINISHDRAWING_DESC     236
#define IDS_CFGVAL_DRAWMODE_OUTLINEWIDTH 237
#define IDC_ET_HINT                     238
#define IDS_MENU_OUTLINEINC_NAME        238
#define IDS_MENU_OUTLINEINC_DESC        239
#define IDS_MENU_IMAGEZOOM              240
#define IDS_MENU_OUTLINEDEC_NAME        240
#define IDS_MENU_ZOOMIN_NAME            241
#define IDS_MENU_OUTLINEDEC_DESC        241
#define IDC_ET_NEARDENSLABEL2           242
#define IDS_MENU_ZOOMIN_DESC            242
#define IDS_MENU_SHAPEBRUSH_NAME        242
#define IDS_HELP_COLORAARRGGBB          242
#define IDS_MENU_ZOOMOUT_NAME           243
#define IDS_MENU_SHAPEBRUSH_DESC        243
#define IDS_HELP_COLORAARRGGBB2         243
#define IDS_OPENCUSTOMPATTERN           243
#define IDS_MENU_ZOOMOUT_DESC           244
#define IDC_ET_SINGLE                   244
#define IDS_MENU_FILLSTYLE              244
#define IDS_MENU_ZOOMAUTO_NAME          245
#define IDC_ET_POLY                     245
#define IDS_MENU_SWAPCOLORS_NAME        245
#define IDS_MENU_ZOOMAUTO_DESC          246
#define IDS_MENU_SWAPCOLORS_DESC        246
#define IDS_MENU_SWAPCOLORS             247
#define IDS_FILLPROPS_VIEWNAME          248
#define IDS_CFGID_2DEDIT_VIEWPORTSYNC_NAME 249
#define IDS_CFGID_2DEDIT_VIEWPORTSYNC_DESC 250
#define IDS_CFGID_2DEDIT_PASTETOOL_NAME 251
#define IDS_CFGID_2DEDIT_PASTETOOL_DESC 252
#define IDI_MENU_SWAPCOLORS             253
#define IDS_HELP_CLOSED                 253
#define IDS_FILLSTYLE_PATTERN_NAME      254
#define IDS_CFGID_2DEDIT_CONTEXTMENU_DESC 255
#define IDS_MENU_GRID                   256
#define IDI_ICON1                       256
#define IDS_MENU_GRID0_NAME             257
#define IDS_MENU_GRID0_DESC             258
#define IDC_CGTL_FILTER                 258
#define IDS_MENU_GRID1_NAME             259
#define IDC_CGTL_SYNCGRP                259
#define IDS_MENU_GRID1_DESC             260
#define IDC_ET_ORIGINALSIZE             260
#define IDS_MENU_GRID8_NAME             261
#define IDC_ET_FILLAREA                 261
#define IDS_MENU_GRID8_DESC             262
#define IDC_CG_ENTIREIMAGE              262
#define IDS_CFGID_2DEDIT_GESTUREROTATELEFT_NAME 264
#define IDC_CGRE_CLR1ID                 265
#define IDS_CFGID_2DEDIT_GESTUREROTATERIGHT_NAME 265
#define IDS_MENU_CONFIGUREGESTURES      265
#define IDC_CGRE_CLR2ID                 266
#define IDS_MENU_COMPOSEDVIEW           266
#define IDC_CGRE_CLR2LABEL              267
#define IDS_MN_COMPOSEDVIEW             267
#define IDS_MN_SHOWCOMPOSED             267
#define IDS_MD_COMPOSEDVIEW             268
#define IDS_MD_SHOWCOMPOSED             268
#define IDS_MENU_WINDOWRENDERING        269
#define IDC_CGRE_SELID                  270
#define IDS_MN_RENDERNEAREST            270
#define IDC_CGRE_SELLABEL               271
#define IDS_MD_RENDERNEAREST            271
#define IDC_CGRE_FILLID                 272
#define IDS_MN_RENDERLINEAR             272
#define IDC_CG_SELID                    273
#define IDC_CGRE_VIEWID                 273
#define IDS_MD_RENDERLINEAR             273
#define IDS_MN_RENDERCOVERAGE           274
#define IDS_MD_RENDERCOVERAGE           275
#define IDD_MODIFYHANDLE                275
#define IDC_ET_TILTEDELLIPSE            276
#define IDS_EDITTOOL_MAGICWAND          278
#define IDD_CONFIGGUI_CUSTOMTOOL        278
#define IDS_MN_SHOWTRANSPARENT          278
#define IDS_TOOLDESC_MAGICWAND          279
#define IDD_CONFIGGUI_CUSTOMTOOLS       279
#define IDS_MD_SHOWTRANSPARENT          279
#define IDS_TOOLNAME_SIMPLESELECT       280
#define IDD_MANAGECUSTOMTOOLS           280
#define IDS_MN_SHOWLAYER                280
#define IDS_TOOLDESC_SIMPLESELECT       281
#define IDD_ADDCUSTOMTOOL               281
#define IDS_MD_SHOWLAYER                281
#define IDS_TOOLNAME_BRUSH              282
#define IDI_PRESET_ADD                  282
#define IDS_MN_RENDERINVERTED           282
#define IDC_CGRE_FILLIDLABEL            283
#define IDS_TOOLDESC_BRUSH              283
#define IDI_PRESET_MANAGE               283
#define IDS_MD_RENDERINVERTED           283
#define IDS_GOID_UNDO                   284
#define IDS_GOID_REDO                   285
#define IDD_FILLSTYLE_NOOPTIONS         285
#define IDS_GOID_APPLY                  286
#define IDD_FILLSTYLE_UNAPPLICABLE      286
#define IDS_GOID_OUTLINE                287
#define IDD_CONFIGURELAYEREFFECT        287
#define IDS_GOID_FILLED                 288
#define IDS_GOID_DRAWMODE               288
#define IDS_GOID_COMBINED               289
#define IDS_GOID_SWITCHSTYLE            289
#define IDS_GOID_AUTOZOOM               290
#define IDS_GESTURE_RIGHT               291
#define IDS_GESTURE_LEFT                292
#define IDS_GOID_SWAPCOLORS             293
#define IDS_GESTURE_RIGHTLEFT           294
#define IDI_LAYER_OPERATION             294
#define IDS_GESTURE_LEFTRIGHT           295
#define IDD_ADDSWATCHES                 295
#define IDS_GESTURE_DOWN                296
#define IDS_GESTURE_UP                  297
#define IDI_STATUS_RECTSIZE             297
#define IDS_GESTURE_DOWNUP              298
#define IDI_STATUS_COORDS               298
#define IDS_GESTURE_UPDOWN              299
#define IDS_GESTURE_DOWNRIGHT           300
#define IDS_GESTURE_DOWNLEFT            301
#define IDS_GESTURE_UPRIGHT             302
#define IDS_GESTURE_UPLEFT              303
#define IDS_GESTURE_RECTANGLE           304
#define IDS_GESTURE_CIRCLE              305
#define IDS_GESTURE_ARROWUP             306
#define IDS_GESTURE_ARROWDOWN           307
#define IDS_GESTURE_ARROWLEFT           308
#define IDC_MH_X                        308
#define IDS_GESTURE_ARROWRIGHT          309
#define IDC_MH_Y                        309
#define IDI_ICON2                       309
#define IDS_GESTURE_HOURGLASS           310
#define IDC_CGRE_PASTELABEL             310
#define IDI_NO_PAINT                    310
#define IDS_MENU_CONFIGUREGESTURES_NAME 311
#define IDC_CGRE_PASTE                  311
#define IDI_ICON3                       311
#define IDS_MENU_CONFIGUREGESTURES_DESC 312
#define IDC_CGRE_SELECTIONMASK          312
#define IDS_GESTURE_LETTERA             313
#define IDS_GESTURE_LETTERZ             314
#define IDS_GESTURE_LETTERM             315
#define IDC_CHECK1                      315
#define IDC_CT_USECOLOR1                315
#define IDC_CT_OUTENABLED               315
#define IDS_GESTURE_LETTERW             316
#define IDS_GESTURE_LETTERN             317
#define IDC_CGRE_SELECTIONID            317
#define IDS_GESTURE_LETTERIN            318
#define IDC_CGRE_SELECTIONIDLABEL       318
#define IDS_GESTURE_CROSS               319
#define IDC_CT_ICONID                   319
#define IDS_MG_GESTURES_HELP            320
#define IDC_CT_USECOLOR2                320
#define IDS_MG_OPERATION_HELP           321
#define IDC_CT_USETOOLID                321
#define IDS_MENU_STRETCHSELECTION_NAME  322
#define IDC_CT_USETOOLCONFIG            322
#define IDS_MENU_RESTORESELECTION_NAME  323
#define IDC_CT_USESTYLEID               323
#define IDS_MENU_HANDLECOORDINATES_NAME 324
#define IDC_CT_STYLEID                  324
#define IDS_MENU_HANDLECOORDINATES_DESC 325
#define IDC_CT_USESTYLECONFIG           325
#define IDS_MENU_DELETEVERTEX_NAME      326
#define IDC_CT_STYLECONFIG              326
#define IDS_MENU_DELETEVERTEX_DESC      327
#define IDC_CT_USEBLENDMODE             327
#define IDS_CFGID_2DEDIT_SELECTIONSUPPORT_NAME 328
#define IDC_CT_BLENDMODE                328
#define IDS_CFGID_2DEDIT_SELECTIONSUPPORT_DESC 329
#define IDC_CT_USERASTERMODE            329
#define IDS_POINTDESC_POLYLINEVERTEX    330
#define IDC_CT_USEFILLMODE              330
#define IDS_POINTDESC_POLYLINEEDGE      331
#define IDC_CT_FILLMODE                 331
#define IDS_TOOLNAME_ERASER             332
#define IDC_CT_USECOORDSMODE            332
#define IDS_TOOLDESC_ERASER             333
#define IDC_CT_COORDSMODE               333
#define IDS_MENU_CUSTOMTOOLS            334
#define IDC_CT_CONFIG                   334
#define IDS_MENU_OWCONST_DESC           335
#define IDC_CT_HIDEMANAGER              335
#define IDS_MENU_OWPOPUP_DESC           336
#define IDC_CT_TOOLSYNC                 336
#define IDS_TOOLDESC_LINE               337
#define IDC_CT_CLR1SYNC                 337
#define IDS_TOOLDESC_CURVE              338
#define IDC_CT_CLR2SYNC                 338
#define IDS_TOOLDESC_POLYGON            339
#define IDC_CT_CLR1LABEL                339
#define IDS_TOOLDESC_ELLIPSE            340
#define IDC_CT_CLR2LABEL                340
#define IDS_TOOLDESC_RECTANGLE          341
#define IDC_CT_TOOLLABEL                341
#define IDS_TOOLDESC_PSHADOW            342
#define IDC_RT_CONFIG                   342
#define IDS_TOOLDESC_DROPPER            343
#define IDC_CT_NAME                     343
#define IDS_TOOLDESC_FLOODFILL          344
#define IDC_CT_ICONIDLABEL              344
#define IDS_TOOLDESC_TEXT               345
#define IDC_CT_DESC                     345
#define IDS_TOOLDESC_PENCIL             346
#define IDC_CT_TOOLID                   346
#define IDS_PENCILSHAPES                347
#define IDC_CT_TOOLCONFIG               347
#define IDS_LISTBUTTONNAMES             348
#define IDC_CT_USEOUTLINE               348
#define IDS_RWTOOLS_FILTER              349
#define IDC_CT_OUTLINE                  349
#define IDS_RWTOOLS_OPEN                350
#define IDC_CT_SEPLINE                  350
#define IDS_RWTOOLS_SAVE                351
#define IDS_CFGID_CT_COMMANDNAME_NAME   352
#define IDC_ET_ARBITRARYXFORM           352
#define IDS_CFGID_CT_COMMANDNAME_DESC   353
#define IDS_CFGID_CT_COMMANDDESC_NAME   354
#define IDC_CG_IMAGEMASKID              354
#define IDS_CFGID_CT_COMMANDDESC_DESC   355
#define IDS_CFGID_ICONID_NAME           356
#define IDS_CFGID_ICONID_DESC           357
#define IDS_CFGID_CT_USECOLOR1_NAME     358
#define IDS_CFGID_CT_COLOR1_NAME        359
#define IDS_CFGID_CT_COLOR1_DESC        360
#define IDS_CFGID_CT_USECOLOR2_NAME     361
#define IDS_CFGID_CT_COLOR2_NAME        362
#define IDS_CFGID_CT_COLOR2_DESC        363
#define IDS_CFGID_CT_ENABLER_DESC       364
#define IDS_CFGID_CT_USETOOLID_NAME     365
#define IDS_CFGID_CT_TOOLID_NAME        366
#define IDS_CFGID_CT_TOOLID_DESC        367
#define IDS_CFGID_CT_USETOOLCONFIG_NAME 368
#define IDC_LE_CONFIG                   368
#define IDS_CFGID_CT_TOOLCONFIG_NAME    369
#define IDS_CFGID_CT_TOOLCONFIG_DESC    370
#define IDS_CFGID_CT_USESTYLEID_NAME    371
#define IDS_CFGID_CT_STYLEID_NAME       372
#define IDS_CFGID_CT_STYLEID_DESC       373
#define IDS_CFGID_CT_USESTYLECONFIG_NAME 374
#define IDS_CFGID_CT_STYLECONFIG_NAME   375
#define IDS_CFGID_CT_STYLECONFIG_DESC   376
#define IDS_CFGID_CT_USEBLENDMODE_NAME  377
#define IDS_CFGID_CT_BLENDMODE_NAME     378
#define IDS_CFGID_CT_BLENDMODE_DESC     379
#define IDS_CFGID_CT_USERASTERMODE_NAME 380
#define IDS_CFGID_CT_RASTERMODE_NAME    381
#define IDS_CFGID_CT_RASTERMODE_DESC    382
#define IDS_CFGID_CT_USEFILLMODE_NAME   383
#define IDS_CFGID_CT_FILLMODE_NAME      384
#define IDS_CFGID_CT_FILLMODE_DESC      385
#define IDS_CFGID_CT_USECOORDSMODE_NAME 386
#define IDS_CFGID_CT_COORDSMODE_NAME    387
#define IDS_CFGID_CT_COORDSMODE_DESC    388
#define IDS_CFGID_CT_COMMANDS_NAME      389
#define IDS_CFGID_CT_COMMANDS_DESC      390
#define IDS_CFGID_CT_HIDEMANAGER_NAME   391
#define IDS_CFGID_CT_HIDEMANAGER_DESC   392
#define IDS_MN_ADDCUSTOMTOOL            393
#define IDS_MD_ADDCUSTOMTOOL            394
#define IDS_MN_MANAGECUSTOMTOOLS        395
#define IDS_MD_MANAGECUSTOMTOOLS        396
#define IDS_CFGID_CT_USEOUTLINE_NAME    397
#define IDS_CFGID_CT_OUTLINE_NAME       398
#define IDS_CFGID_CT_OUTLINE_DESC       399
#define IDS_CFGID_CT_COMMANDSHORTCUT_NAME 400
#define IDS_CFGID_CT_COMMANDSHORTCUT_DESC 401
#define IDS_GOID_SWITCHTOOL             402
#define IDS_CFGID_GESTUREOUTLINEDDELTA_NAME 403
#define IDS_CFGID_GESTUREOUTLINEDDELTA_DESC 404
#define IDS_CFGID_GESTUREMODETYPE_NAME  405
#define IDS_CFGID_GESTUREMODETYPE_DESC  406
#define IDS_GENERICERROR                407
#define IDS_TOOLNAME_RETOUCH            408
#define IDS_TOOLDESC_RETOUCH            409
#define IDS_RETOUCH_BRIGHTEN            410
#define IDS_RETOUCH_DARKEN              411
#define IDS_RETOUCH_SHARPEN             412
#define IDS_RETOUCH_SOFTEN              413
#define IDS_RETOUCH_ADD                 414
#define IDS_RETOUCH_MUL                 415
#define IDC_ASG_COLOR2                  415
#define IDS_HELP_BRUSHSHAPE             416
#define IDC_ASG_STEP_SPIN               416
#define IDS_HELP_BRUSHSIZE              417
#define IDC_ASG_STEP_EDIT               417
#define IDS_HELP_BRUSHBLUR              418
#define IDS_HELP_BRUSHFLOW              419
#define IDS_HELP_BRUSHPRESSURE          420
#define IDS_HELP_RECTANGULARXFORM       421
#define IDS_HELP_PERSPECTIVEXFORM       422
#define IDS_HELP_BEZIERXFORM            423
#define IDS_TOOLDESC_SELECT             424
#define IDS_TOOLDESC_TRANSFORMATION     425
#define IDS_COLORSWATCH_VIEWNAME        426
#define IDS_HELP_COLORSWATCH            427
#define IDC_LE_SEQUENCE                 427
#define IDS_MENU_DELETECOLORS_NAME      428
#define IDC_LE_PREVIEW                  428
#define IDS_MENU_DELETECOLORS_DESC      429
#define IDC_LE_PREVIEWLABEL             429
#define IDS_MENU_LOADCOLORS_NAME        430
#define IDC_LE_OPERATIONS               430
#define IDS_MENU_LOADCOLORS_DESC        431
#define IDC_LE_OPERATIONS_LABEL         431
#define IDS_MENU_INSERTCOLORS_NAME      432
#define IDC_CT_TOOLCFG                  432
#define IDS_MENU_INSERTCOLORS_DESC      433
#define IDC_CT_STYLECFG                 433
#define IDS_MENU_PRESETCOLORS_DESC      434
#define IDC_CT_OUTCOLOR                 434
#define IDS_MENU_PRESETCOLORS_DEFAULT   435
#define IDC_CT_OUTWIDTH                 435
#define IDS_MENU_PRESETCOLORS_WINDOWS   436
#define IDS_MENU_PRESETCOLORS_WEB       437
#define IDS_MENU_SAVECOLORS_NAME        438
#define IDS_MENU_SAVECOLORS_DESC        439
#define IDS_DROPMSG_PASTEIMAGE          440
#define IDS_FORMATFILTER_RWCS           441
#define IDS_FORMATFILTER_ACO            442
#define IDS_TOOLNAME_METASELECT         443
#define IDS_TOOLDESC_METASELECT         444
#define IDS_HELP_MATCHRGBA              445
#define IDS_HELP_MATCHHUE               446
#define IDS_HELP_MATCHALPHA             447
#define IDS_HELP_MATCHBRIGHTNESS        448
#define IDS_HELP_MULTIPOINT             449
#define IDS_HELP_EDGESNAP               450
#define IDS_HELP_EDGESMOOTH             451
#define IDS_HELP_DASHPATTERN            452
#define IDS_HELP_RETOUCHEFFECT          453
#define IDS_HELP_RETOUCHSTRENGTH        454
#define IDS_BRUSHSHAPE_ROUND            455
#define IDS_BRUSHSHAPE_SQUARE           456
#define IDS_BRUSHSHAPE_SLASH            457
#define IDS_HELP_MATCHALL               458
#define IDS_HELP_FSPATTERN              459
#define IDS_HELP_FSCENTER               460
#define IDS_HELP_FSCURVE                461
#define IDS_RETOUCH_DESATURATE          462
#define IDS_RETOUCH_REPLACEHUE          463
#define IDS_ET_TEXTALIGNMENTS           464
#define IDS_HELP_FSPATH                 465
#define IDS_HELP_BLURBACKGROUND         466
#define IDS_HELP_DROPSHADOW             467
#define IDS_HELP_SHADOWSIZE             468
#define IDS_HELP_SHADOWDENSITY          469
#define IDS_HELP_ADDREFLECTION          470
#define IDS_TOOLNAME_STYLIZE            471
#define IDS_TOOLDESC_STYLIZE            472
#define IDS_LAYERPROPS_VIEWNAME         473
#define IDS_MENU_MANAGELAYERS           474
#define IDS_MN_APPENDLAYER              475
#define IDS_MD_APPENDLAYER              476
#define IDS_MN_DELETELAYER              477
#define IDS_MD_DELETELAYER              478
#define IDS_CFGID_COMMANDCODES_NAME     479
#define IDS_CFGID_COMMANDCODES_DESC     480
#define IDS_MN_DUPLICATELAYER           481
#define IDS_MD_DUPLICATELAYER           482
#define IDS_LAYER_COPYOF                483
#define IDS_LAYER_MERGED                485
#define IDS_MN_MOVELAYERUP              486
#define IDS_MN_MOVELAYERDOWN            487
#define IDS_MD_MOVELAYER                488
#define IDS_MN_IMPORTLAYER              491
#define IDS_MD_IMPORTLAYER              492
#define IDS_MN_EXPORTLAYER              493
#define IDS_MD_EXPORTLAYER              494
#define IDS_MN_LAYEROPERATION           495
#define IDS_MD_LAYEROPERATION           496
#define IDS_LAYERPROPS_BLENDING         497
#define IDS_HELP_LAYEROPACITY           498
#define IDS_HELP_LAYERBLENDING          499
#define IDS_HELP_DEFAULTCOLORS          500
#define IDS_HELP_COLORBUTTON            504
#define IDS_CFGVAL_CPGTYPE_PICKER       505
#define IDS_CFGVAL_CPGTYPE_COMPACT      506
#define IDS_GLBCFG_COLOR_NAME           507
#define IDS_GLBCFG_COLOR_DESC           508
#define IDS_CFGID_GCC_BUTTONPAL_NAME    509
#define IDS_CFGID_GCC_BUTTONPAL_DESC    510
#define IDS_CFGID_GCC_FACTOR_NAME       511
#define IDS_CFGID_GCC_FACTOR_DESC       512
#define IDS_CFGID_GCC_DECIMALS_NAME     513
#define IDS_CFGID_GCC_DECIMALS_DESC     514
#define IDS_CFGID_GCC_DLGVIEW_NAME      515
#define IDS_CFGID_GCC_DLGVIEW_DESC      516
#define IDS_COLOR_CURRENTTOLAST         517
#define IDS_HELP_COLORHISTORY           518
#define IDS_HELP_COLOR2DAREA            519
#define IDS_HELP_COLOR1DAREA            520
#define IDS_HELP_COLORALPHAAREA         521
#define IDS_HELP_COLORCHANNEL           522
#define IDS_HELP_COLORNUMBER            523
#define IDS_CFGVAL_CSGTYPE_SWATCH       524
#define IDS_CFGVAL_CSGTYPE_HISTORY      525
#define IDS_CFGID_CLRSWCH_SWATCHFLAGS_NAME 526
#define IDS_CFGID_CLRSWCH_SWATCHFLAGS_DESC 527
#define IDS_MENU_STOCKCOLORS_NAME       528
#define IDS_MENU_STOCKCOLORS_DESC       529
#define IDS_MENU_CUSTOMCOLORS_NAME      530
#define IDS_MENU_CUSTOMCOLORS_DESC      531
#define IDS_CFGID_GCC_GAMMA_NAME        532
#define IDS_CFGID_GCC_GAMMA_DESC        533
#define IDS_TOOLNAME_ALPHA              534
#define IDS_LAYEREFFECTTOOLBAR          535
#define IDS_CFGID_CLRPICK_LABEL_NAME    539
#define IDS_CFGID_CLRPICK_LABEL_DESC    540

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         436
#define _APS_NEXT_SYMED_VALUE           543
#endif
#endif
