//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RWDrawing.rc
//
#define IDS_PROJNAME                    100
#define IDS_HELP_COLORBUTTON            144
#define IDS_HELP_FSPATH                 145
#define IDS_HELP_FSPATTERN              146
#define IDS_OPENCUSTOMPATTERN           147
#define IDS_BRUSHSHAPE_ROUND            148
#define IDS_BRUSHSHAPE_SLASH            149
#define IDS_BRUSHSHAPE_SQUARE           150
#define IDS_FILLSTYLE_CONICAL_NAME      151
#define IDS_FILLSTYLE_LINEAR_NAME       152
#define IDS_FILLSTYLE_PATTERN_NAME      153
#define IDS_FILLSTYLE_RADIAL_NAME       154
#define IDS_FILLSTYLE_SOLID_NAME        155
#define IDS_HELP_ADDREFLECTION          156
#define IDS_HELP_BEVELJOIN              157
#define IDS_HELP_BEZIERXFORM            158
#define IDS_HELP_BLUR                   159
#define IDS_HELP_BLURBACKGROUND         160
#define IDS_HELP_BRUSHBLUR              161
#define IDS_HELP_BRUSHFLOW              162
#define IDS_HELP_BRUSHPRESSURE          163
#define IDS_HELP_BRUSHSHAPE             164
#define IDS_HELP_BRUSHSIZE              165
#define IDS_HELP_BUTTCAP                166
#define IDS_HELP_CLOSED                 167
#define IDS_HELP_CUBICFILTERING         168
#define IDS_HELP_DASHPATTERN            169
#define IDS_HELP_DEFAULTCOLORS          170
#define IDS_HELP_DROPSHADOW             171
#define IDS_HELP_EDGESMOOTH             172
#define IDS_HELP_EDGESNAP               173
#define IDS_HELP_FARDENS                174
#define IDS_HELP_FONT                   175
#define IDS_HELP_FSCENTER               176
#define IDS_HELP_GRADIENTCTL            177
#define IDS_HELP_GRADIENTSTOPCLR        178
#define IDS_HELP_NOFILTERING            179
#define IDS_HELP_LINEARFILTERING        180
#define IDS_HELP_TEXT                   181
#define IDS_HELP_WIDTH                  182
#define IDS_HELP_MITERJOIN              183
#define IDS_HELP_ROUNDJOIN              184
#define IDS_HELP_RADIUS                 185
#define IDS_HELP_SQUARECAP              186
#define IDS_HELP_ROUNDEDCAP             187
#define IDS_HELP_TOLERANCE              188
#define IDS_HELP_NEARDENS               189
#define IDS_HELP_RECTANGULARXFORM       190
#define IDS_HELP_PERSPECTIVEXFORM       191
#define IDS_HELP_MATCHRGBA              192
#define IDS_HELP_MATCHHUE               193
#define IDS_HELP_MATCHALPHA             194
#define IDS_HELP_MATCHBRIGHTNESS        195
#define IDS_HELP_MULTIPOINT             196
#define IDS_HELP_RETOUCHEFFECT          197
#define IDS_HELP_RETOUCHSTRENGTH        198
#define IDS_HELP_MATCHALL               199
#define IDI_HOWTO_SHADOW                200
#define IDS_HELP_SHADOWSIZE             200
#define IDS_HELP_SHADOWDENSITY          201
#define IDC_ET_FONT                     202
#define IDS_HELP_GRADIENTSTOPPOS        202
#define IDS_TOOLNAME_SELECT             203
#define IDS_TOOLDESC_SELECT             204
#define IDC_ET_ANGLE                    204
#define IDS_TOOLNAME_PENCIL             205
#define IDC_ET_ANGLESPIN                205
#define IDS_TOOLDESC_PENCIL             206
#define IDC_ET_DEGREES                  206
#define IDC_ET_PENCILSHAPE              207
#define IDS_TOOLNAME_LINE               207
#define IDC_ET_BEND                     207
#define IDS_TOOLDESC_LINE               208
#define IDC_ET_BENDSPIN                 208
#define IDS_TOOLNAME_RECTANGLE          209
#define IDC_ET_BENDUNIT                 209
#define IDS_TOOLDESC_RECTANGLE          210
#define IDC_ET_BRUSHIMAGE               210
#define IDC_ET_FONT_STYLE               210
#define IDS_TOOLNAME_FLOODFILL          211
#define IDC_ET_BLURLABEL                211
#define IDS_TOOLDESC_FLOODFILL          212
#define IDC_ET_SCATTER                  212
#define IDS_TOOLNAME_DROPPER            213
#define IDC_ET_ROTATE                   213
#define IDS_TOOLDESC_DROPPER            214
#define IDC_ET_RESIZE                   214
#define IDS_TOOLNAME_ELLIPSE            215
#define IDC_ET_SMOOTHING_CHECK          215
#define IDS_TOOLDESC_ELLIPSE            216
#define IDC_ET_SMOOTHING_SLIDER         216
#define IDC_ET_TEXT                     217
#define IDS_TOOLNAME_TEXT               217
#define IDS_TOOLDESC_TEXT               218
#define IDS_TOOLNAME_CURVE              219
#define IDD_EDITTOOL_TEXT               220
#define IDC_ET_FARDENS                  220
#define IDS_TOOLDESC_CURVE              220
#define IDC_ET_NOFILTERING              221
#define IDC_ET_RGBA                     221
#define IDS_TOOLNAME_PSHADOW            221
#define IDC_ET_LINEARFILTERING          222
#define IDC_ET_HUE                      222
#define IDS_TOOLDESC_PSHADOW            222
#define IDC_ET_CUBICFILTERING           223
#define IDC_ET_BRIGHTNESS               223
#define IDS_TOOLNAME_POLYGON            223
#define IDC_ET_SEPLINE1                 224
#define IDS_TOOLDESC_POLYGON            224
#define IDC_ET_SEPLINE2                 225
#define IDD_EDITTOOL_MOVESELECT         225
#define IDS_TOOLNAME_TRANSFORMATION     225
#define IDI_EDITTOOL_TEXTART            226
#define IDS_TOOLDESC_TRANSFORMATION     226
#define IDS_TOOLNAME_MAGICWAND          227
#define IDS_TOOLDESC_MAGICWAND          228
#define IDI_EDITTOOL_ERASER             229
#define IDD_EDITTOOL_FLOODFILL          229
#define IDS_TOOLNAME_SIMPLESELECT       229
#define IDS_TOOLDESC_SIMPLESELECT       230
#define IDS_TOOLNAME_BRUSH              231
#define IDI_EDITTOOL_STYLIZE            232
#define IDD_EDITTOOL_SHADOW             232
#define IDS_TOOLDESC_BRUSH              232
#define IDS_TOOLNAME_ERASER             233
#define IDI_FILLSTYLE_SOLID             234
#define IDC_ET_TOLERANCE                234
#define IDS_TOOLDESC_ERASER             234
#define IDI_FILLSTYLE_PATTERN           235
#define IDS_TOOLNAME_RETOUCH            235
#define IDI_FILLSTYLE_LINEAR            236
#define IDS_TOOLDESC_RETOUCH            236
#define IDI_FILLSTYLE_RADIAL            237
#define IDS_TOOLNAME_METASELECT         237
#define IDI_FILLSTYLE_CONICAL           238
#define IDS_TOOLDESC_METASELECT         238
#define IDC_ET_BLUR                     239
#define IDI_STATUS_RECTSIZE             239
#define IDS_TOOLNAME_STYLIZE            239
#define IDC_ET_BLURMAX                  240
#define IDS_TOOLDESC_STYLIZE            240
#define IDC_ET_NEARDENSLABEL            241
#define IDS_TOOLNAME_ALPHA              241
#define IDC_ET_FARDENSLABEL             242
#define IDC_ET_NEARDENS                 243
#define IDS_PENCILSHAPES                243
#define IDS_RETOUCH_ADD                 244
#define IDC_CURSOR1                     244
#define IDS_RETOUCH_BRIGHTEN            245
#define IDS_RETOUCH_DARKEN              246
#define IDS_RETOUCH_DESATURATE          247
#define IDS_RETOUCH_MUL                 248
#define IDS_RETOUCH_REPLACEHUE          249
#define IDS_RETOUCH_SHARPEN             250
#define IDI_ICON1                       250
#define IDS_RETOUCH_SOFTEN              251
#define IDI_ICON2                       251
#define IDS_ET_TEXTALIGNMENTS           252
#define IDI_FILLSTYLE_DIAMOND           252
#define IDC_ET_TOLERANCESPIN            253
#define IDS_MENU_DELETEVERTEX_DESC      253
#define IDI_FILLSTYLE_SPHERE            253
#define IDC_ET_NEARDENSSPIN             254
#define IDS_MENU_DELETEVERTEX_NAME      254
#define IDI_ICON3                       254
#define IDC_ET_FARDENSSPIN              255
#define IDS_MENU_RESTORESELECTION_DESC  255
#define IDC_CURSOR2                     255
#define IDC_ET_HELPIMAGE                256
#define IDS_MENU_RESTORESELECTION_NAME  256
#define IDC_ET_HELPTEXT                 257
#define IDD_EDITTOOL_BRUSH              257
#define IDS_MENU_STRETCHSELECTION_DESC  257
#define IDD_EDITTOOL_VISTAGLASS         258
#define IDS_MENU_STRETCHSELECTION_NAME  258
#define IDS_POINTDESC_POLYLINEEDGE      259
#define IDS_POINTDESC_POLYLINEVERTEX    260
#define IDS_TOOLNAME_MOVE               261
#define IDS_TOOLDESC_MOVE               262
#define IDS_MENU_CROP2SELECTION_NAME    263
#define IDS_MENU_CROP2SELECTION_DESC    264
#define IDS_TOOLNAME_FILL               265
#define IDS_TOOLDESC_FILL               266
#define IDS_TOOLNAME_LASSO              267
#define IDS_TOOLDESC_LASSO              268
#define IDS_FILLSTYLE_DIAMOND_NAME      269
#define IDS_FILLSTYLE_SPHERE_NAME       270
#define IDD_EDITTOOL_PENCIL             276
#define IDD_EDITTOOL_RETOUCH            283
#define IDD_EDITTOOL_MAGICWAND          284
#define IDC_ET_SIMPLEFILL               284
#define IDC_ET_MULTIPOINT               285
#define IDC_ET_ALPHA                    287
#define IDC_ET_SELECTION                288
#define IDC_ET_TOLERANCELABEL           289
#define IDC_ET_BLURBACKGROUND           292
#define IDC_ET_DROPSHADOW               293
#define IDC_ET_ADDREFLECTION            294
#define IDC_ET_SIZESPIN                 296
#define IDC_ET_BRUSHSHAPE               297
#define IDC_ET_SIZEEDIT                 298
#define IDC_ET_SIZEUNIT                 299
#define IDC_ET_BLUREDIT                 300
#define IDC_ET_BLURSPIN                 301
#define IDC_ET_BLURUNIT                 302
#define IDC_ET_FLOWSPIN                 303
#define IDC_ET_FLOWUNIT                 304
#define IDC_ET_BOLD                     315
#define IDC_ET_SIZECHECK                315
#define IDC_ET_ELLIPSESECTOR            316
#define IDC_ET_BLURCHECK                316
#define IDC_ET_FLOWCHECK                317
#define IDC_ET_ITALIC                   355
#define IDC_ET_SIZE                     356
#define IDC_ET_PIXELS                   357
#define IDC_ET_RETOUCHEFFECT            358
#define IDC_ET_FLOWEDIT                 362
#define IDC_ET_RETROUCHSTREDIT          363
#define IDC_ET_RETROUCHSTRSPIN          364
#define IDC_ET_RETROUCHSTRUNIT          365
#define IDC_ET_EDGESNAP                 366
#define IDC_ET_EDGESMOOTH               367
#define IDC_ET_ALIGN                    369
#define IDC_ET_SHADOWSIZE               370
#define IDC_ET_SHADOWSIZE_UNIT          371
#define IDC_ET_SHADOWDENSITY            372
#define IDC_ET_SHADOWDENSITY_UNIT       373

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         217
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
