
#pragma once

#include <ConfigCustomGUIImpl.h>

static OLECHAR const CFGID_SELECTIONSYNCID[] = L"SelectionSync";
static OLECHAR const CFGID_OPERATION[] = L"Operation";


class ATL_NO_VTABLE CConfigGUIMaskDlg :
	public CCustomConfigWndImpl<CConfigGUIMaskDlg>,
	public CDialogResize<CConfigGUIMaskDlg>
{
public:
	CConfigGUIMaskDlg()
	{
	}

	enum { IDD = IDD_CONFIGGUI_MASK };

	BEGIN_MSG_MAP(CConfigGUIMaskDlg)
		CHAIN_MSG_MAP(CDialogResize<CConfigGUIMaskDlg>)
		CHAIN_MSG_MAP(CCustomConfigWndImpl<CConfigGUIMaskDlg>)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
	END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CConfigGUIMaskDlg)
		DLGRESIZE_CONTROL(IDC_CGM_OPERATION, DLSZ_DIVSIZE_X(2))
		DLGRESIZE_CONTROL(IDC_CGM_SELSYNCIDLABEL, DLSZ_DIVMOVE_X(2))
		DLGRESIZE_CONTROL(IDC_CGM_SELSYNCID, DLSZ_DIVMOVE_X(2)|DLSZ_DIVSIZE_X(2))
		DLGRESIZE_CONTROL(IDC_CGM_CONFIG, DLSZ_SIZE_X|DLSZ_SIZE_Y)
	END_DLGRESIZE_MAP()

	BEGIN_CONFIGITEM_MAP(CConfigGUIMaskDlg)
		CONFIGITEM_EDITBOX(IDC_CGM_SELSYNCID, CFGID_SELECTIONSYNCID)
		CONFIGITEM_COMBOBOX(IDC_CGM_OPERATION, CFGID_OPERATION)
		CONFIGITEM_SUBCONFIG_NOMARGINS(IDC_CGM_CONFIG, CFGID_OPERATION)
	END_CONFIGITEM_MAP()

	LRESULT OnInitDialog(UINT UNREF(a_uMsg), WPARAM UNREF(a_wParam), LPARAM UNREF(a_lParam), BOOL& a_bHandled)
	{
		DlgResize_Init(false, false, 0);

		return 1;
	}
};

