//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RWOperationImagePhoto.rc
//
#define IDS_PROJNAME                    100
#define IDS_RASTERIMAGEREMOVEHUE_NAME   101
#define IDS_CFGID_HUE_NAME              102
#define IDS_CFGID_CURVE_NAME            103
#define IDS_CFGID_HUE_DESC              104
#define IDS_CFGID_CURVE_DESC            105
#define IDS_HELP_CURVE                  106
#define IDS_CUSTCFG_MORECOLORS          107
#define IDS_RASTERIMAGEAUTOCONTRAST_NAME 108
#define IDS_CUSTCFG_PICKCOLOR           109
#define IDS_CFGID_X_AXIS                110
#define IDS_CFGID_INTERPOLATION         111
#define IDS_CFGID_X_AXIS_HUE            112
#define IDS_CFGID_X_AXIS_COLOR          113
#define IDS_CFGID_INTERPOLATION_BSPLINE 114
#define IDS_CFGID_INTERPOLATION_LINEAR  115
#define IDS_RASTERIMAGEGRAYSCALE_NAME   116
#define IDS_CFGID_COLOR_NAME            117
#define IDS_CFGID_COLOR_DESC            118
#define IDS_CFGID_AUTO_LEVELS_NAME      119
#define IDS_CFGID_AL_TYPE_NAME          119
#define IDS_CFGID_AUTO_LEVELS_DESC      120
#define IDS_CFGID_AL_TYPE_DESC          120
#define IDS_CFGID_TOLERANCE_NAME        121
#define IDS_CFGID_TOLERANCE_DESC        122
#define IDS_RASTERIMAGECANVASSIZE_NAME  123
#define IDS_CFGID_HLS_HUE_NAME          124
#define IDS_CFGID_HLS_SATURATION_NAME   125
#define IDS_CFGID_HLS_LIGHTNESS_NAME    126
#define IDS_CFGID_HLS_AREA_NAME         127
#define IDS_CFGID_HLS_AREA1_NAME        128
#define IDS_CFGID_HLS_AREA2_NAME        129
#define IDS_CFGID_HLS_AREA3_NAME        130
#define IDS_CFGID_HLS_AREA4_NAME        131
#define IDS_CFGID_CS_POSITION_NAME      132
#define IDS_CFGID_CS_POSITION_TOP       133
#define IDS_CFGID_CS_POSITION_TOP_LEFT  134
#define IDS_CFGID_CS_POSITION_TOP_RIGHT 135
#define IDS_CFGID_CS_POSITION_CENTER    136
#define IDS_CFGID_CS_POSITION_LEFT      137
#define IDS_CFGID_CS_POSITION_RIGHT     138
#define IDS_CFGID_CS_POSITION_BOTTOM    139
#define IDS_CFGID_CS_POSITION_BOTTOM_LEFT 140
#define IDS_CFGID_CS_POSITION_BOTTOM_RIGHT 141
#define IDS_CFGID_CS_RELATIVE_NAME      142
#define IDS_CFGID_CS_SIZE_X_NAME        143
#define IDS_CFGID_CS_SIZE_Y_NAME        144
#define IDS_CFGID_CS_COLOR_NAME         145
#define IDS_CFGID_CS_COLOR_FILL_NAME    146
#define IDS_RASTERIMAGEHLS_NAME         147
#define IDS_EDITTOOL_REDEYE_NAME        148
#define IDS_EDITTOOL_REDEYE_DESC        149
#define IDS_EDITTOOL_CROP_NAME          150
#define IDS_EDITTOOL_CROP_DESC          151
#define IDS_CROP_NOPROPORTIONS          152
#define IDS_TOOLNAME_CLONE              153
#define IDS_TOOLDESC_CLONE              154
#define IDS_HELP_STANDARD               155
#define IDS_HELP_HIGHFREQ               156
#define IDS_HELP_LOWFREQ                157
#define IDS_HELP_RELATIVE               158
#define IDS_DOCOPREMOVENOISE_NAME       159
#define IDS_DOCOPWATERMARK_NAME         160
#define IDS_CFGID_WM_XPOSITION_NAME     161
#define IDS_CFGID_WM_XPOSITION_DESC     162
#define IDS_CFGID_WM_YPOSITION_NAME     163
#define IDS_CFGID_WM_YPOSITION_DESC     164
#define IDS_CFGID_WM_MARGINS_NAME       165
#define IDS_CFGID_WM_EFFECT_NAME        167
#define IDS_CFGID_WM_OPACITY_NAME       167
#define IDS_CFGID_WM_EFFECT_DESC        168
#define IDS_CFGID_WM_OPACITY_DESC       168
#define IDS_CFGID_WM_TYPE_NAME          169
#define IDS_CFGID_WM_TYPE_DESC          170
#define IDS_CFGID_WM_IMAGE_NAME         173
#define IDS_CFGID_WM_IMAGE_DESC         174
#define IDS_CFGID_WM_TEXT_NAME          175
#define IDS_CFGID_WM_TEXT_DESC          176
#define IDS_CFGID_WM_FONT_NAME          177
#define IDS_CFGID_WM_FONT_DESC          178
#define IDS_CFGID_WM_STYLE_NAME         179
#define IDS_CFGID_WM_BOLD_NAME          179
#define IDS_CFGID_WM_STYLE_DESC         180
#define IDS_CFGID_WM_BOLD_DESC          180
#define IDS_CFGID_WMS_NORMAL            181
#define IDS_CFGID_WM_ITALIC_NAME        181
#define IDS_CFGID_WMS_BOLD              182
#define IDS_CFGID_WM_ITALIC_DESC        182
#define IDS_CFGID_WMS_ITALIC            183
#define IDS_CFGID_WM_SHADOW_NAME        183
#define IDS_CFGID_WMS_ITALICBOLD        184
#define IDS_CFGID_WM_SHADOW_DESC        184
#define IDS_CFGID_WM_ANGLE_NAME         185
#define IDS_CFGID_WM_ANGLE_DESC         186
#define IDS_CFGID_WM_ALIGNMENT_NAME     187
#define IDS_CFGID_WM_ALIGNMENT_DESC     188
#define IDS_CFGID_WMA_LEFT              189
#define IDS_CFGID_WMA_CENTER            190
#define IDS_CFGID_WMA_RIGHT             191
#define IDS_CFGID_WM_SIZETYPE_NAME      192
#define IDS_CFGID_WM_SIZETYPE_DESC      193
#define IDS_CFGID_WMH_ABSOLUTE          194
#define IDS_CFGID_WMH_RELATIVE          195
#define IDS_CFGID_WM_ABSSIZE_DESC       197
#define IDS_CUSTCFG_MORECOLORS2         199
#define IDS_WATERMARK_LAYERNAME         199
#define IDS_CUSTCFG_COLORNAMES          200
#define IDS_RASTERIMAGELEVELS_NAME      200
#define IDD_CONFIGGUI_REMOVEHUE         201
#define IDC_CGRHUE_CURVECTL             201
#define IDS_CUSTCFG_DEFAULTCOLOR        201
#define IDS_CFGVAL_ALT_CONTRAST         201
#define IDC_CGRHUE_COLORBAR             202
#define IDS_SELECTIMAGEWATERMARK        202
#define IDC_CGRHUE_RADIO_HUE            203
#define IDS_DOCOPGLOW_NAME              203
#define IDC_CGRHUE_RADIO_COLOR          204
#define IDS_CFGID_SG_RADIUS_NAME        204
#define IDC_CGRHUE_RADIO_BSPLINE        205
#define IDS_CFGID_SG_RADIUS_DESC        205
#define IDC_CGRHUE_RADIO_LINEAR         206
#define IDS_CFGID_SG_INTENSITY_NAME     206
#define IDC_CGRHUE_GROUP_AXISX          207
#define IDS_CFGID_SG_INTENSITY_DESC     207
#define IDC_ET_SHAPETOOL                207
#define IDC_CGRHUE_GROUP_INTER          208
#define IDS_CFGID_SG_COLORED_NAME       208
#define IDC_CGRHUE_GROUP_POINT          209
#define IDS_CFGID_SG_COLORED_DESC       209
#define IDC_CGRHUE_ALPHABAR             210
#define IDS_CFGID_SG_MASKID_NAME        210
#define IDS_CUSTCFG_FROMPIXEL           211
#define IDS_CFGVAL_ALT_LEVELS           211
#define IDS_CFGID_SG_MASKID_DESC        212
#define IDS_TOOLNAME_BUBBLE             213
#define IDS_TOOLDESC_BUBBLE             214
#define IDC_CGRHUE_X                    215
#define IDS_RASTERIMAGEVIGNETTING_NAME  215
#define IDC_CGRHUE_Y                    216
#define IDS_CFGID_VIG_AUTO_UNVIG_NAME   216
#define IDS_CFGID_VIG_AUTO_UNVIG_DESC   217
#define IDS_CFGID_VIG_COLOR_NAME        218
#define IDI_ICON1                       219
#define IDS_CFGID_VIG_COLOR_DESC        219
#define IDI_ICON2                       220
#define IDS_CFGID_VIG_CURVE_NAME        220
#define IDS_CFGID_VIG_CURVE_DESC        221
#define IDC_CGCS_COLOR_FILL             222
#define IDD_EDITTOOL_CROP               222
#define IDS_CFGID_VIG_INTERPOLATION_NAME 222
#define IDS_CFGID_VIG_INTERPOLATION_DESC 223
#define IDC_ET_SEPLINE1                 224
#define IDD_EDITTOOL_CLONE              224
#define IDI_PICK_COLOR_ADD              224
#define IDS_HELP_PERSPECTIVECROP        224
#define IDC_ET_SEPLINE2                 225
#define IDI_PICK_COLOR                  225
#define IDS_HELP_NORMALCROP             225
#define IDI_PICK_COLOR_REMOVE           226
#define IDS_HELP_JPEGCROP               226
#define IDC_CGRHUE_X_SPIN               227
#define IDI_EDITTOOL_BUBBLE             227
#define IDD_CONFIGGUI_VIGNETTING        227
#define IDS_HELP_ASPECTRATIO            227
#define IDC_CGRHUE_Y_SPIN               228
#define IDS_CFGID_SS_COLOR_NAME         228
#define IDD_CONFIGGUI_SEAMCARVING       228
#define IDD_CONFIGGUI_SOFTENSKIN        229
#define IDS_CFGID_SS_COLOR_DESC         229
#define IDS_CFGID_SS_STRENGTH_NAME      230
#define IDD_EDITTOOL_BUBBLE             230
#define IDS_CFGID_SS_STRENGTH_DESC      231
#define IDS_RASTERIMAGE_SOFTENSKIN_NAME 232
#define IDI_FILLSTYLE_WOOD              232
#define IDS_CFGID_WM_COLOR_DESC         233
#define IDD_FILLSTYLE_WOOD              233
#define IDS_CFGID_CS_RELATIVE_DESC      234
#define IDD_FILLSTYLE_CLOUDS            234
#define IDC_CGCS_EMPTY_FILL             235
#define IDS_CFGID_CS_SIZE_DESC          235
#define IDS_CFGID_CS_POSITION_DESC      236
#define IDC_ET_ASPECTRATIO              237
#define IDS_CFGID_CS_COLOR_FILL_DESC    237
#define IDI_FILLSTYLE_CLOUDS            237
#define IDC_ET_STANDARD                 238
#define IDS_CFGID_CS_COLOR_DESC         238
#define IDC_ET_HIGHFREQ                 239
#define IDS_RASTERIMAGESEAMCARVING_NAME 239
#define IDC_ET_LOWFREQ                  240
#define IDS_CFGID_SC_SIZEX_NAME         240
#define IDI_RESET_GRAY                  240
#define IDC_ET_RELATIVE                 241
#define IDS_CFGID_SC_SIZEX_DESC         241
#define IDI_LEVEL_AUTO                  241
#define IDC_ET_HINT                     242
#define IDS_CFGID_SC_SIZEY_NAME         242
#define IDS_CFGID_SC_SIZEY_DESC         243
#define IDS_CFGID_SC_SELMODE_NAME       244
#define IDS_CFGID_SC_SELMODE_DESC       245
#define IDS_CFGVAL_SCSM_IGNORE          246
#define IDS_CFGVAL_SCSM_PROTECT         247
#define IDC_ET_NORMALCROP               248
#define IDC_CG_EFFECT                   248
#define IDS_CFGVAL_SCSM_REMOVE          248
#define IDC_ET_JPEGCROP                 249
#define IDS_CFGID_SC_SELSYCID_NAME      249
#define IDC_ET_PERSPECTIVECROP          250
#define IDS_CFGID_SC_SELSYCID_DESC      250
#define IDS_HELP_BUBBLECOLOR            251
#define IDS_RASTERIMAGE_UNSHARPMASK_NAME 252
#define IDS_CFGID_BLUM_RADIUS_NAME      253
#define IDI_ICON3                       253
#define IDC_CG_STYLE                    254
#define IDS_CFGID_BLUM_RADIUS_DESC      254
#define IDS_CFGID_BLUM_AMOUNT_NAME      255
#define IDS_CFGID_BLUM_AMOUNT_DESC      256
#define IDS_CFGID_BLUM_THRESHOLD_NAME   257
#define IDS_CFGID_BLUM_THRESHOLD_DESC   258
#define IDS_FILLSTYLE_WOOD_NAME         259
#define IDS_FILLSTYLE_WOOD_DESC         260
#define IDS_FILLSTYLE_CLOUDS_NAME       261
#define IDC_CGRHUE_COLOR                262
#define IDS_FILLSTYLE_CLOUDS_DESC       262
#define IDS_CFGID_L_INBLACK_NAME        266
#define IDS_CFGID_L_INBLACK_DESC        267
#define IDS_CFGID_L_INWHITE_NAME        268
#define IDS_CFGID_L_INWHITE_DESC        269
#define IDS_CFGID_L_GAMMA_NAME          270
#define IDS_CFGID_L_GAMMA_DESC          271
#define IDC_CG_STYLE_LABEL              272
#define IDS_CFGID_L_OUTBLACK_NAME       272
#define IDS_CFGID_L_OUTBLACK_DESC       273
#define IDS_CFGID_L_OUTWHITE_NAME       274
#define IDS_CFGID_L_OUTWHITE_DESC       275
#define IDC_EDIT2                       276
#define IDC_CGSC_SIZEY                  276
#define IDC_ETW_STRETCH                 276
#define IDS_LEVELS_TIPS                 276
#define IDD_EDITTOOL_SHAPESHIFT         276
#define IDS_CFGID_RN_METHOD_NAME        277
#define IDS_CFGID_RN_METHOD_DESC        278
#define IDS_CFGVAL_RNM_BLUR9OF25        279
#define IDS_CFGVAL_RNM_BLURENERGY       280
#define IDS_CFGID_RN_THRESHOLD_NAME     281
#define IDS_CFGID_RN_THRESHOLD_DESC     282
#define IDS_EDITTOOL_SHAPESHIFT_NAME    283
#define IDS_EDITTOOL_SHAPESHIFT_DESC    284
#define IDC_CGHLS_HUEBAR1               294
#define IDC_CGHLS_HUEBAR2               295
#define IDC_ET_SIZESPIN                 296
#define IDC_CGHLS_HUEAREA               298
#define IDC_ET_SIZEEDIT                 298
#define IDC_ET_SIZEUNIT                 299
#define IDC_CGVIG_AUTO                  312
#define IDC_CGVIG_CURVECTL              313
#define IDC_CGVIG_BAR                   314
#define IDC_CGVIG_GROUP_INTER           315
#define IDC_CGVIG_GROUP_POINT           316
#define IDC_CGVIG_RADIO_BSPLINE         317
#define IDC_CGVIG_RADIO_LINEAR          318
#define IDC_CGVIG_X                     319
#define IDC_CGVIG_X_SPIN                320
#define IDC_CGVIG_Y                     321
#define IDC_CGVIG_Y_SPIN                322
#define IDC_CGVIG_COLOR                 323
#define IDC_CGSS_STRENGTH_TEXT          324
#define IDC_CGSS_STRENGTH_SLIDER        325
#define IDC_CGSS_STRENGTH_EDIT          326
#define IDC_CGSS_STRENGTH_SPIN          327
#define IDC_CGSS_COLOR                  328
#define IDC_ET_BUBBLECOLOR              329
#define IDC_CGSC_SIZEX                  330
#define IDC_CGSC_SELMODE                331
#define IDC_EDIT3                       332
#define IDC_CGSC_SELID                  332
#define IDC_ETW_SCALE                   345
#define IDC_ETW_ANGLE                   350
#define IDC_ETW_RINGS                   351
#define IDC_ETW_TURBULENCE              352
#define IDC_ETW_FIBRES                  353
#define IDC_ETW_GAIN                    354
#define IDC_ETW_AUTOCENTER              355
#define IDC_ETW_SEED                    356
#define IDC_ETW_DEFAULTCOLORS           357
#define IDC_ETC_AMOUNT                  359
#define IDC_ETC_BIAS                    360
#define IDC_ET_SIZELABEL                373
#define IDC_ET_INTENSITYCHECK           374
#define IDC_ET_INTENSITYEDIT            375
#define IDC_ET_INTENSITYSPIN            376
#define IDC_ET_INTENSITYUNIT            377
#define IDC_ET_INTENSITYLABEL           378
#define IDC_ETW_COLOR1                  379
#define IDC_ETW_COLOR2                  380

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         380
#define _APS_NEXT_SYMED_VALUE           347
#endif
#endif
