
#pragma once

static OLECHAR const CFGID_BMPFORMAT[] = L"Format";
static LONG const CFGVAL_BMPFORMAT_32BIT = 32;
static LONG const CFGVAL_BMPFORMAT_24BIT = 24;
static LONG const CFGVAL_BMPFORMAT_16BIT = 16;
static LONG const CFGVAL_BMPFORMAT_8BIT = 8;
static LONG const CFGVAL_BMPFORMAT_8BITRLE = 9;
static LONG const CFGVAL_BMPFORMAT_4BIT = 4;
static LONG const CFGVAL_BMPFORMAT_4BITRLE = 5;
static LONG const CFGVAL_BMPFORMAT_1BIT = 1;
static LONG const CFGVAL_BMPFORMAT_BITFIELDS = 100;
static LONG const CFGVAL_BMPFORMAT_MASK = 0xff;
static OLECHAR const CFGID_DITHERING[] = L"Dithering";
//static LONG const CFGVAL_DITHERING_NONE = 0;
static LONG const CFGVAL_DITHERINGFLAG = 0x80000000;

